### ISSUE TITLE
instances in CWBWH

### ISSUE THREAD

**Issue by tigrazone** [jan-van-bergen/GPU-Raytracer#31]
Hello! 
How processed instances in CWBWH? 
How this nodes is marked in cuda and c++?
Thank you

**Comment by jan-van-bergen** [comment]
Hey,
Instances are handled the same for all BVH types, so the CWBVH is not special or anything.

During Mesh loading the filename is used to check if a cached version of the Mesh already exists, if so it is given the same handle to the underlying mesh data as before.
https://github.com/jan-van-bergen/GPU-Raytracer/blob/1247418f168534249f46daf2f22b93d4af951d3f/Src/Assets/AssetManager.h#L51

So two different instances are just two different Meshes that make use of the same underlying MeshData/BVH. There is no other explicit marking that they are instances.

As an example you can look at this file: https://github.com/jan-van-bergen/GPU-Raytracer/blob/1247418f168534249f46daf2f22b93d4af951d3f/Data/instancing/scene.xml#L48
Even though there is no explicit instancing, the AssetLoader will reuse the same MeshData for all Meshes since they all share the filename `lucy.obj`.

**Comment by tigrazone** [comment]
Thank you for explaination
