### ISSUE TITLE
Why add a dummy node in SBVH?

### ISSUE THREAD

**Issue by xue-fc** [jan-van-bergen/GPU-Raytracer#33]
https://github.com/jan-van-bergen/GPU-Raytracer/blob/463267ff55a0ae73c0efc79db300dd7a60000117/Src/BVH/Builders/SBVHBuilder.cpp#L50-L54

At line 53, why a dummy node is inserted? 
In my opinion, only the memory of root node should be allocated before calling build_sbvh().

Thanks.

**Comment by jan-van-bergen** [comment]
This is a remnant from the fact that this code was originally based on my [CPU Raytracer project](https://github.com/jan-van-bergen/CPU-Raytracer).
The idea there was that since each BVHNode2 is 32 bytes, you can exactly fit the 2 children of a node inside a single 64 byte cacheline. This cacheline would then (hopefully) need to be loaded only *once* from RAM during BVH traversal, thereby improving performance.

Note that this is assumes that the BVH nodes array itself is aligned to 64 bytes ([which I *did* ensure in the CPU tracer](https://github.com/jan-van-bergen/CPU-Raytracer/blob/d0d26d179cf91cf514149b0cede94fd1c3993041/BottomLevelBVH.cpp#L69)), but I didn't actually ensure in this project. So the benefit is sort of lost here.

I guess the reason I didnt bother here is that I expect less of a performance improvement since I dont actually traverse the BVH on the CPU side. On the other hand maybe the BVHOptimizer could benefit from the cache locality, so perhaps I should try out using an aligned allocation for the BVH nodes here as well.

**Comment by xue-fc** [comment]
I got it. Thank you very much.
