### ISSUE TITLE
imask and meta field in BVH8 converter

### ISSUE THREAD

**Issue by xue-fc** [jan-van-bergen/GPU-Raytracer#34]
According to [Ylitie et al. 2017](https://research.nvidia.com/sites/default/files/publications/ylitie2017hpg-paper.pdf), each BVH8 node stores an 8-bit imask field to indicate which of the children are internal nodes. 

So I think variable node_internal_count in line 309 and line 307 should be replaced by variable i. Figure 5 in the paper shows this pattern. 
https://github.com/jan-van-bergen/GPU-Raytracer/blob/a3742589ea64bd59996615d45810bbffdb413e89/Src/BVH/Converters/BVH8Converter.cpp#L306-L312

Thanks.

**Comment by jan-van-bergen** [comment]
Yes you are right, very good catch!

I don't think it will affect performance or correctness, but I have now [updated](https://github.com/jan-van-bergen/GPU-Raytracer/commit/bb6d2cbde69328feae42e594b08c0339527d4ed2) this to be like the paper since its probably best to just follow it unless there is a good reason not to.

Thank you!
