### ISSUE TITLE
Is it necessary to scale tMin and tMax

### ISSUE THREAD

**Issue by xue-fc** [jan-van-bergen/GPU-Raytracer#39]
After hitting a new mesh, only origin and direction are transformed.
https://github.com/jan-van-bergen/GPU-Raytracer/blob/6559ae2241c8fdea0ddaec959fe1a47ec9b3ab0d/Src/CUDA/Raytracing/BVH2.h#L105-L109

But _transform_inv_ may contains scale transformation.
https://github.com/jan-van-bergen/GPU-Raytracer/blob/6559ae2241c8fdea0ddaec959fe1a47ec9b3ab0d/Src/Renderer/Mesh.cpp#L24-L27

If scale is not identity matrix, _ray.direction_ will not be a normalized vector after transformation. Then we get wrong _ray_hit.t_ in this algorithm.
https://github.com/jan-van-bergen/GPU-Raytracer/blob/6559ae2241c8fdea0ddaec959fe1a47ec9b3ab0d/Src/CUDA/Raytracing/Triangle.h#L148-L174

So I think we should scale _tMin_ and _tMax_ when transforming _ray.origin_ and _ray.direction_.

Thanks for your any reply.

**Comment by Pjbomb2** [comment]
Just letting you know that unfortunately Jan has passed away, and as such there wont be any further updates to this project
However, since I use an identitcal system to Jan here for bvh and triangle traversal, its not an issue.  not sure entirely why myself(havent bothered to figure out yet), by the distances are always correct and dont need scaling in my experience thus far.

**Comment by xue-fc** [comment]
I'm very sorry to hear about the loss. His work has been very helpful to me.

If only ray.direction is scaled, the calculated tHit will be the correct value multiplied by scale. But I guess this offset will be counteracted by the transformation on triangle data, finally we get correct distance.

**Comment by Pjbomb2** [comment]
yeah...
Again, I use basically the same system, and the hit distances are correct(compared to rasterized GBuffer), no offset is needed

**Comment by xue-fc** [comment]
Thanks for your help!
